export {
  faSpinner,
  faCheck,
  faEllipsisV,
  faTrash,
  faDownload,
  faVolumeOff,
  faVolumeDown,
  faVolumeUp,
  faPlay,
  faPause,
  faRedo,
  faUndo,
  faSave,
  faAngleDoubleRight,
  faAngleRight,
  faAngleLeft,
  faAngleDoubleLeft,
  faChevronDown,
  faEdit,
} from '@fortawesome/free-solid-svg-icons'
